### ISSUE TITLE
Allow the From account to be specified by index (rather than hex)

### ISSUE THREAD

**Issue by peterbroadhurst** [kaleido-io/ethconnect#12]
Currently the request to submit a transaction must include the full `from` address:
```yaml
headers:
  type: SendTransaction
from: 0xc07F8826B4Fe5fc4E63724ad828C13f57e98852B
to: 0xe1cda5bf18c1693d46c352a13154a90e55f8c179
params:
  - 4276993775
gas: 1000000
method:
  name: set
  inputs:
    - name: x
      type: uint256
```

When using node-based signing (currently the only option) it would be convenient to be able to be specify the from address by index, within the wallet owned by the node.
Then the full `from` address could be returned on the receipt.
